"$schema" = "schemas/schema.json"

[default]
description = "Default permissions for the rusqlite plugin."
permissions = [
    "allow-load",
    "allow-execute",
    "allow-select",
    "allow-close",
    "allow-begin-transaction",
    "allow-commit-transaction",
    "allow-rollback-transaction",
]
